apiVersion: 1

datasources:
  - name: PostgreSQL-SNMP
    type: postgres
    access: proxy
    url: snmp-psql:5432
    database: snmptraps
    user: snmpuser
    secureJsonData:
      password: snmppass123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    version: 1
    editable: true